### ISSUE TITLE
Can't compile with GHC 9.2.1

### ISSUE THREAD

**Issue by LeventErkok** [tsurucapital/vector-th-unbox#6]
```
Preprocessing library for vector-th-unbox-0.2.1.9..
Building library for vector-th-unbox-0.2.1.9..
[1 of 1] Compiling Data.Vector.Unboxed.Deriving

Data/Vector/Unboxed/Deriving.hs:59:19: error:
    • Couldn't match type ‘[Pat] -> Pat’ with ‘Pat’
      Expected: Pat -> Pat
        Actual: Type -> [Pat] -> Pat
    • Probable cause: ‘(.)’ is applied to too few arguments
      In the first argument of ‘first’, namely ‘(ConP mvName . (: []))’
      In the first argument of ‘(<$>)’, namely
        ‘first (ConP mvName . (: []))’
      In a stmt of a 'do' block:
        mv <- first (ConP mvName . (: [])) <$> newPatExp "mvec"
   |
59 |     mv  <- first (ConP mvName . (:[])) <$> newPatExp "mvec"
   |                   ^^^^^^^^^^^^^^^^^^^

Data/Vector/Unboxed/Deriving.hs:60:19: error:
    • Couldn't match type ‘[Pat] -> Pat’ with ‘Pat’
      Expected: Pat -> Pat
        Actual: Type -> [Pat] -> Pat
    • Probable cause: ‘(.)’ is applied to too few arguments
      In the first argument of ‘first’, namely ‘(ConP mvName . (: []))’
      In the first argument of ‘(<$>)’, namely
        ‘first (ConP mvName . (: []))’
      In a stmt of a 'do' block:
        mv' <- first (ConP mvName . (: [])) <$> newPatExp "mvec'"
   |
60 |     mv' <- first (ConP mvName . (:[])) <$> newPatExp "mvec'"
   |                   ^^^^^^^^^^^^^^^^^^^

Data/Vector/Unboxed/Deriving.hs:61:19: error:
    • Couldn't match type ‘[Pat] -> Pat’ with ‘Pat’
      Expected: Pat -> Pat
        Actual: Type -> [Pat] -> Pat
    • Probable cause: ‘(.)’ is applied to too few arguments
      In the first argument of ‘first’, namely ‘(ConP vName . (: []))’
      In the first argument of ‘(<$>)’, namely
        ‘first (ConP vName . (: []))’
      In a stmt of a 'do' block:
        v <- first (ConP vName . (: [])) <$> newPatExp "vec"
   |
61 |     v   <- first (ConP vName  . (:[])) <$> newPatExp "vec"
   |                   ^^^^^^^^^^^^^^^^^^^
```

**Comment by LeventErkok** [comment]
There's a patch in hackage.head:

https://gitlab.haskell.org/ghc/head.hackage/-/blob/master/patches/vector-th-unbox-0.2.1.9.patch

Perhaps this is as easy as applying this package and releasing..

**Comment by fumieval** [comment]
Thanks for reporting. I've just uploaded [0.2.2](https://hackage.haskell.org/package/vector-th-unbox-0.2.2)
